FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

COPY grpcPOC/GrpcServer/ ./GrpcServer/
WORKDIR /src/GrpcServer
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:10.0
WORKDIR /app
COPY --from=build /app/publish .
EXPOSE 5001
ENV ASPNETCORE_URLS=http://+:5001
ENTRYPOINT ["dotnet", "GrpcServer.dll"]
